"""Add Chef Table

Revision ID: ac85d6dc8d90
Revises: cc78a79b8480
Create Date: 2023-11-19 10:17:50.248479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac85d6dc8d90'
down_revision: Union[str, None] = 'cc78a79b8480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chefs', ['id'])
    op.drop_constraint('chefs_chef_id_fkey', 'chefs', type_='foreignkey')
    op.drop_column('chefs', 'chef_id')
    op.add_column('recipes', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'chefs', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'chef_id')
    op.add_column('chefs', sa.Column('chef_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chefs_chef_id_fkey', 'chefs', 'chefs', ['chef_id'], ['id'])
    op.drop_constraint(None, 'chefs', type_='unique')
    # ### end Alembic commands ###
