# Generated by Django 4.2.6 on 2023-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
