# Generated by Django 4.2.6 on 2023-10-28 13:21

from django.db import migrations


def set_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item_record in items:
        if item_record.price <= 10:
            item_record.rarity = 'Rare'
        elif item_record.price <= 20:
            item_record.rarity = 'Very Rare'
        elif item_record.price <= 30:
            item_record.rarity = 'Extremely Rare'
        else:
            item_record.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items, ['rarity'])


def set_rarity_default(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    rarity_default = item_model._meta.get_field("rarity").default

    for item in item_model.objects.all():
        item.rarity = rarity_default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=set_rarity_default)
    ]
